//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_SemWithSyhov
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseWork
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public byte Course { get; set; }
        public string Mark { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
